import type { User, Team, TeamMember, Task } from "./types"

export const demoUsers: User[] = [
  {
    id: 1,
    email: "admin@taskmanager.com",
    name: "Admin User",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    email: "john@taskmanager.com",
    name: "John Doe",
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    email: "jane@taskmanager.com",
    name: "Jane Smith",
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    email: "mike@taskmanager.com",
    name: "Mike Johnson",
    created_at: new Date().toISOString(),
  },
]

export const demoTeams: Team[] = [
  {
    id: 1,
    name: "Development Team",
    description: "Frontend and backend development team",
    owner_id: 1,
    created_at: new Date().toISOString(),
    member_count: 3,
    task_count: 4,
    owner_name: "Admin User",
  },
  {
    id: 2,
    name: "Design Team",
    description: "UI/UX design and creative team",
    owner_id: 2,
    created_at: new Date().toISOString(),
    member_count: 2,
    task_count: 2,
    owner_name: "John Doe",
  },
  {
    id: 3,
    name: "Marketing Team",
    description: "Marketing and growth team",
    owner_id: 3,
    created_at: new Date().toISOString(),
    member_count: 2,
    task_count: 1,
    owner_name: "Jane Smith",
  },
]

export const demoTasks: Task[] = [
  {
    id: 1,
    title: "Setup project structure",
    description: "Initialize the project with proper folder structure",
    team_id: 1,
    assigned_to: 2,
    created_by: 1,
    status: "completed",
    priority: "high",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    team_name: "Development Team",
    assigned_to_name: "John Doe",
    created_by_name: "Admin User",
  },
  {
    id: 2,
    title: "Design user interface",
    description: "Create wireframes and mockups for the application",
    team_id: 2,
    assigned_to: 3,
    created_by: 2,
    status: "in_progress",
    priority: "high",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    team_name: "Design Team",
    assigned_to_name: "Jane Smith",
    created_by_name: "John Doe",
  },
  {
    id: 3,
    title: "Implement authentication",
    description: "Build secure login and registration system",
    team_id: 1,
    assigned_to: 4,
    created_by: 1,
    status: "in_progress",
    priority: "high",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    team_name: "Development Team",
    assigned_to_name: "Mike Johnson",
    created_by_name: "Admin User",
  },
  {
    id: 4,
    title: "Create marketing strategy",
    description: "Develop comprehensive marketing plan",
    team_id: 3,
    assigned_to: 4,
    created_by: 3,
    status: "todo",
    priority: "medium",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    team_name: "Marketing Team",
    assigned_to_name: "Mike Johnson",
    created_by_name: "Jane Smith",
  },
  {
    id: 5,
    title: "Write unit tests",
    description: "Add comprehensive test coverage",
    team_id: 1,
    assigned_to: 2,
    created_by: 1,
    status: "todo",
    priority: "medium",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    team_name: "Development Team",
    assigned_to_name: "John Doe",
    created_by_name: "Admin User",
  },
]

export const demoTeamMembers: TeamMember[] = [
  {
    id: 1,
    team_id: 1,
    user_id: 1,
    role: "owner",
    joined_at: new Date().toISOString(),
    user_name: "Admin User",
    user_email: "admin@taskmanager.com",
  },
  {
    id: 2,
    team_id: 1,
    user_id: 2,
    role: "member",
    joined_at: new Date().toISOString(),
    user_name: "John Doe",
    user_email: "john@taskmanager.com",
  },
  {
    id: 3,
    team_id: 1,
    user_id: 4,
    role: "member",
    joined_at: new Date().toISOString(),
    user_name: "Mike Johnson",
    user_email: "mike@taskmanager.com",
  },
]
